# Generated by Django 3.1.6 on 2021-02-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
            ],
        ),
    ]
